#!/usr/bin/env python3
"""Render a markdown leaderboard from results/experiments.jsonl.

Not committed as state by default — regenerate on demand. The append-only
result history is the source of truth; this is a view over it. The
``--write`` flag is the exception: it writes a snapshot leaderboard to a
specific file (e.g., ``results/rollup.aquitanian.md``). Snapshots are
allowed because the rollup is a deterministic function of the result
stream, not a hand-edited artifact.

Per-metric ordering:
  * compression_delta_v0 — sorted by ``score`` desc.
  * local_fit_v0         — sorted by ``score_control_z`` desc.

Examples:
  python3 scripts/rollup.py
  python3 scripts/rollup.py --metric compression_delta_v0
  python3 scripts/rollup.py --metric local_fit_v0 --pool aquitanian --top 50
  python3 scripts/rollup.py --metric local_fit_v0 --by source-pool
  python3 scripts/rollup.py --metric local_fit_v0 --pool aquitanian --top 50 \
      --write results/rollup.aquitanian.md
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from collections import defaultdict
from pathlib import Path


_REPO_ROOT = Path(__file__).resolve().parent.parent
_DEFAULT_RESULTS = _REPO_ROOT / "results" / "experiments.jsonl"


def load_rows(path: Path) -> list[dict]:
    if not path.exists():
        return []
    rows: list[dict] = []
    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def _sort_key(row: dict) -> float:
    """Per-metric sort key. Higher = better; we sort descending."""
    if row["metric"] == "local_fit_v0":
        return float(row.get("score_control_z", 0.0))
    return float(row["score"])


def _infer_pool(row: dict) -> str | None:
    """Infer the source pool from ``hypothesis_path``.

    Convention: hypotheses generated by ``scripts/generate_candidates.py``
    live under ``hypotheses/auto/<pool>/...``. For other paths (curated,
    legacy) no pool is inferred and the row groups under ``unspecified``.
    """
    parts = Path(row.get("hypothesis_path", "")).parts
    if len(parts) >= 4 and parts[0] == "hypotheses" and parts[1] == "auto":
        return parts[2]
    return None


def _render_compression_delta(group: list[dict]) -> list[str]:
    out = ["| rank | score | bps_baseline | bps_mapped | hypothesis | run_id | ran_at |"]
    out.append("|---:|---:|---:|---:|---|---|---|")
    for i, r in enumerate(group, 1):
        out.append(
            "| {rank} | {score:.4f} | {bb:.4f} | {bm:.4f} | `{hyp}` | `{rid}` | {at} |".format(
                rank=i,
                score=r["score"],
                bb=r.get("bits_per_sign_baseline", float("nan")),
                bm=r.get("bits_per_sign_mapped", float("nan")),
                hyp=r["hypothesis_path"],
                rid=r["run_id"][:8],
                at=r["ran_at"],
            )
        )
    return out


def _render_local_fit(group: list[dict]) -> list[str]:
    out = ["| rank | score_control_z | score | hypothesis | run_id | ran_at |"]
    out.append("|---:|---:|---:|---|---|---|")
    for i, r in enumerate(group, 1):
        out.append(
            "| {rank} | {z:.4f} | {score:.4f} | `{hyp}` | `{rid}` | {at} |".format(
                rank=i,
                z=float(r.get("score_control_z", 0.0)),
                score=r["score"],
                hyp=r["hypothesis_path"],
                rid=r["run_id"][:8],
                at=r["ran_at"],
            )
        )
    return out


def _stats(values: list[float]) -> dict:
    n = len(values)
    if n == 0:
        return {"n": 0, "mean": 0.0, "median": 0.0, "sd": 0.0, "min": 0.0, "max": 0.0,
                "n_z_gt_1": 0, "n_z_gt_2": 0, "n_z_lt_neg1": 0}
    mean = sum(values) / n
    sd = math.sqrt(sum((v - mean) ** 2 for v in values) / n)
    sv = sorted(values)
    median = sv[n // 2] if n % 2 == 1 else 0.5 * (sv[n // 2 - 1] + sv[n // 2])
    return {
        "n": n,
        "mean": mean,
        "median": median,
        "sd": sd,
        "min": sv[0],
        "max": sv[-1],
        "n_z_gt_1": sum(1 for v in values if v > 1.0),
        "n_z_gt_2": sum(1 for v in values if v > 2.0),
        "n_z_lt_neg1": sum(1 for v in values if v < -1.0),
    }


def _render_per_pool_summary(rows: list[dict], top: int) -> list[str]:
    """Group local_fit_v0 rows by inferred source pool and render a summary."""
    by_pool: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        pool = _infer_pool(row) or "unspecified"
        by_pool[pool].append(row)

    out: list[str] = []
    out.append("## local_fit_v0 — per-pool summary\n")
    out.append("| pool | n | mean z | median z | sd z | min z | max z | n(z>+1) | n(z>+2) | n(z<-1) |")
    out.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for pool in sorted(by_pool):
        zs = [float(r.get("score_control_z", 0.0)) for r in by_pool[pool]]
        s = _stats(zs)
        out.append(
            "| {p} | {n} | {mean:+.4f} | {med:+.4f} | {sd:.4f} | {mn:+.4f} | {mx:+.4f} "
            "| {g1} | {g2} | {l1} |".format(
                p=pool, n=s["n"], mean=s["mean"], med=s["median"], sd=s["sd"],
                mn=s["min"], mx=s["max"], g1=s["n_z_gt_1"], g2=s["n_z_gt_2"], l1=s["n_z_lt_neg1"],
            )
        )
    out.append("")
    for pool in sorted(by_pool):
        group = sorted(by_pool[pool], key=_sort_key, reverse=True)[:top]
        out.append(f"### pool: {pool} — top {len(group)} by score_control_z\n")
        out.extend(_render_local_fit(group))
        out.append("")
    return out


def render(
    rows: list[dict],
    metric_filter: str | None,
    pool_filter: str | None,
    top: int | None,
    by_source_pool: bool,
) -> str:
    if pool_filter:
        rows = [r for r in rows if (_infer_pool(r) or "unspecified") == pool_filter]

    by_metric: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        m = row.get("metric")
        if metric_filter and m != metric_filter:
            continue
        by_metric[m].append(row)

    if not by_metric:
        return "_(no result rows match)_\n"

    out: list[str] = []
    if pool_filter:
        out.append(f"_(filter: pool={pool_filter!r})_\n")

    for metric in sorted(by_metric):
        group_all = by_metric[metric]
        n_total = len(group_all)
        s = None
        if metric == "local_fit_v0":
            zs = [float(r.get("score_control_z", 0.0)) for r in group_all]
            s = _stats(zs)
        out.append(f"## {metric} ({n_total} rows)\n")
        if s is not None:
            out.append(
                "Distribution: "
                f"mean z = {s['mean']:+.4f}, "
                f"median = {s['median']:+.4f}, "
                f"sd = {s['sd']:.4f}; "
                f"n(z>+1) = {s['n_z_gt_1']} ({100 * s['n_z_gt_1'] / s['n']:.1f}%), "
                f"n(z>+2) = {s['n_z_gt_2']} ({100 * s['n_z_gt_2'] / s['n']:.1f}%), "
                f"n(z<-1) = {s['n_z_lt_neg1']} ({100 * s['n_z_lt_neg1'] / s['n']:.1f}%)."
            )
            out.append("")

        ordered = sorted(group_all, key=_sort_key, reverse=True)
        if top is not None:
            ordered = ordered[:top]
        if metric == "local_fit_v0":
            out.extend(_render_local_fit(ordered))
        else:
            out.extend(_render_compression_delta(ordered))
        out.append("")

    if by_source_pool:
        local_fit_rows = [
            r for r in rows if r.get("metric") == "local_fit_v0"
        ]
        if local_fit_rows:
            out.append("")
            out.extend(_render_per_pool_summary(local_fit_rows, top or 10))

    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--results",
        type=Path,
        default=_DEFAULT_RESULTS,
        help="Path to results/experiments.jsonl (default: %(default)s).",
    )
    parser.add_argument("--metric", default=None, help="Restrict to a single metric name.")
    parser.add_argument(
        "--pool",
        default=None,
        help="Restrict to a single source pool (inferred from hypothesis_path under "
        "hypotheses/auto/<pool>/).",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=None,
        help="Show only the top N rows per metric (default: all).",
    )
    parser.add_argument(
        "--by",
        choices=["source-pool"],
        default=None,
        help="Append a grouped summary section. 'source-pool' groups local_fit_v0 "
        "rows by inferred source pool.",
    )
    parser.add_argument(
        "--write",
        type=Path,
        default=None,
        help="Write the rendered markdown to this path instead of stdout. The file "
        "is committed-quality output (deterministic given the result stream).",
    )
    args = parser.parse_args(argv)

    rows = load_rows(args.results)
    text = render(
        rows,
        metric_filter=args.metric,
        pool_filter=args.pool,
        top=args.top,
        by_source_pool=(args.by == "source-pool"),
    )
    if args.write:
        args.write.parent.mkdir(parents=True, exist_ok=True)
        args.write.write_text(text, encoding="utf-8")
        print(f"wrote {args.write}", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
