#!/usr/bin/env python3
"""Render a markdown leaderboard from results/experiments.jsonl.

Not committed as state by default — regenerate on demand. The append-only
result history is the source of truth; this is a view over it. The
``--write`` flag is the exception: it writes a snapshot leaderboard to a
specific file (e.g., ``results/rollup.aquitanian.md``). Snapshots are
allowed because the rollup is a deterministic function of the result
stream, not a hand-edited artifact.

Per-metric ordering:
  * compression_delta_v0    — sorted by ``score`` desc.
  * local_fit_v0            — sorted by ``score_control_z`` desc.
  * local_fit_v1            — sorted by ``score`` desc.
  * geographic_genre_fit_v1 — sorted by ``score`` desc.

**Composite leaderboard.** With ``--metrics m1,m2[,...]`` and matching
``--weights w1,w2[,...]`` the rollup joins rows by (hypothesis_path,
hypothesis_hash) across the listed metrics, z-normalizes each metric's
column independently within the joined set, and sorts by the
weighted sum of z-normalized scores. The composite ranking is rendered
with all participating score columns visible.

Examples:
  python3 scripts/rollup.py
  python3 scripts/rollup.py --metric compression_delta_v0
  python3 scripts/rollup.py --metric local_fit_v0 --pool aquitanian --top 50
  python3 scripts/rollup.py --metric local_fit_v0 --by source-pool
  python3 scripts/rollup.py --metric local_fit_v0 --pool aquitanian --top 50 \
      --write results/rollup.aquitanian.md
  python3 scripts/rollup.py --pool aquitanian --top 50 \
      --metrics local_fit_v1,geographic_genre_fit_v1 --weights 0.7,0.3 \
      --normalize zscore --write results/rollup.aquitanian.composite.md
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from collections import defaultdict
from pathlib import Path


_REPO_ROOT = Path(__file__).resolve().parent.parent
_DEFAULT_RESULTS = _REPO_ROOT / "results" / "experiments.jsonl"


def load_rows(path: Path) -> list[dict]:
    if not path.exists():
        return []
    rows: list[dict] = []
    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def _sort_key(row: dict) -> float:
    """Per-metric sort key. Higher = better; we sort descending."""
    if row["metric"] == "local_fit_v0":
        return float(row.get("score_control_z", 0.0))
    return float(row["score"])


def _primary_score_key_for_metric(metric: str) -> str:
    """Field name carrying the higher-is-better score for a metric."""
    if metric == "local_fit_v0":
        return "score_control_z"
    return "score"


def _zscore(values: list[float]) -> list[float]:
    """Standardize to zero mean, unit std. Falls back to all-zeros if std == 0."""
    if not values:
        return []
    mean = sum(values) / len(values)
    var = sum((v - mean) ** 2 for v in values) / len(values)
    sd = math.sqrt(var)
    if sd < 1e-12:
        return [0.0] * len(values)
    return [(v - mean) / sd for v in values]


def _infer_pool(row: dict) -> str | None:
    """Infer the source pool from ``hypothesis_path``.

    Convention: hypotheses generated by ``scripts/generate_candidates.py``
    live under ``hypotheses/auto/<pool>/...``. For other paths (curated,
    legacy) no pool is inferred and the row groups under ``unspecified``.
    """
    parts = Path(row.get("hypothesis_path", "")).parts
    if len(parts) >= 4 and parts[0] == "hypotheses" and parts[1] == "auto":
        return parts[2]
    return None


def _render_compression_delta(group: list[dict]) -> list[str]:
    out = ["| rank | score | bps_baseline | bps_mapped | hypothesis | run_id | ran_at |"]
    out.append("|---:|---:|---:|---:|---|---|---|")
    for i, r in enumerate(group, 1):
        out.append(
            "| {rank} | {score:.4f} | {bb:.4f} | {bm:.4f} | `{hyp}` | `{rid}` | {at} |".format(
                rank=i,
                score=r["score"],
                bb=r.get("bits_per_sign_baseline", float("nan")),
                bm=r.get("bits_per_sign_mapped", float("nan")),
                hyp=r["hypothesis_path"],
                rid=r["run_id"][:8],
                at=r["ran_at"],
            )
        )
    return out


def _render_local_fit(group: list[dict]) -> list[str]:
    out = ["| rank | score_control_z | score | hypothesis | run_id | ran_at |"]
    out.append("|---:|---:|---:|---|---|---|")
    for i, r in enumerate(group, 1):
        out.append(
            "| {rank} | {z:.4f} | {score:.4f} | `{hyp}` | `{rid}` | {at} |".format(
                rank=i,
                z=float(r.get("score_control_z", 0.0)),
                score=r["score"],
                hyp=r["hypothesis_path"],
                rid=r["run_id"][:8],
                at=r["ran_at"],
            )
        )
    return out


def _render_local_fit_v1(group: list[dict]) -> list[str]:
    out = [
        "| rank | score | pos | bigram | length_pen | rare_sign | hypothesis | run_id | ran_at |"
    ]
    out.append("|---:|---:|---:|---:|---:|---:|---|---|---|")
    for i, r in enumerate(group, 1):
        out.append(
            "| {rank} | {score:+.4f} | {pos:+.4f} | {bi:+.4f} | {lp:.4f} | {rs:.3f} | `{hyp}` | `{rid}` | {at} |".format(
                rank=i,
                score=r["score"],
                pos=float(r.get("position_term", 0.0)),
                bi=float(r.get("bigram_term", 0.0)),
                lp=float(r.get("length_penalty", 0.0)),
                rs=float(r.get("rare_sign_correction", 0.0)),
                hyp=r["hypothesis_path"],
                rid=r["run_id"][:8],
                at=r["ran_at"],
            )
        )
    return out


def _render_geographic_genre(group: list[dict]) -> list[str]:
    out = ["| rank | score | region_compat | semantic_compat | hypothesis | run_id | ran_at |"]
    out.append("|---:|---:|---:|---:|---|---|---|")
    for i, r in enumerate(group, 1):
        out.append(
            "| {rank} | {score:.4f} | {rc:.4f} | {sc:.4f} | `{hyp}` | `{rid}` | {at} |".format(
                rank=i,
                score=r["score"],
                rc=float(r.get("region_compat", 0.0)),
                sc=float(r.get("semantic_compat", 0.0)),
                hyp=r["hypothesis_path"],
                rid=r["run_id"][:8],
                at=r["ran_at"],
            )
        )
    return out


def _stats(values: list[float]) -> dict:
    n = len(values)
    if n == 0:
        return {"n": 0, "mean": 0.0, "median": 0.0, "sd": 0.0, "min": 0.0, "max": 0.0,
                "n_z_gt_1": 0, "n_z_gt_2": 0, "n_z_lt_neg1": 0}
    mean = sum(values) / n
    sd = math.sqrt(sum((v - mean) ** 2 for v in values) / n)
    sv = sorted(values)
    median = sv[n // 2] if n % 2 == 1 else 0.5 * (sv[n // 2 - 1] + sv[n // 2])
    return {
        "n": n,
        "mean": mean,
        "median": median,
        "sd": sd,
        "min": sv[0],
        "max": sv[-1],
        "n_z_gt_1": sum(1 for v in values if v > 1.0),
        "n_z_gt_2": sum(1 for v in values if v > 2.0),
        "n_z_lt_neg1": sum(1 for v in values if v < -1.0),
    }


def _render_per_pool_summary(rows: list[dict], top: int) -> list[str]:
    """Group local_fit_v0 rows by inferred source pool and render a summary."""
    by_pool: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        pool = _infer_pool(row) or "unspecified"
        by_pool[pool].append(row)

    out: list[str] = []
    out.append("## local_fit_v0 — per-pool summary\n")
    out.append("| pool | n | mean z | median z | sd z | min z | max z | n(z>+1) | n(z>+2) | n(z<-1) |")
    out.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for pool in sorted(by_pool):
        zs = [float(r.get("score_control_z", 0.0)) for r in by_pool[pool]]
        s = _stats(zs)
        out.append(
            "| {p} | {n} | {mean:+.4f} | {med:+.4f} | {sd:.4f} | {mn:+.4f} | {mx:+.4f} "
            "| {g1} | {g2} | {l1} |".format(
                p=pool, n=s["n"], mean=s["mean"], med=s["median"], sd=s["sd"],
                mn=s["min"], mx=s["max"], g1=s["n_z_gt_1"], g2=s["n_z_gt_2"], l1=s["n_z_lt_neg1"],
            )
        )
    out.append("")
    for pool in sorted(by_pool):
        group = sorted(by_pool[pool], key=_sort_key, reverse=True)[:top]
        out.append(f"### pool: {pool} — top {len(group)} by score_control_z\n")
        out.extend(_render_local_fit(group))
        out.append("")
    return out


def _render_composite(
    rows: list[dict],
    metrics: list[str],
    weights: list[float],
    normalize: str,
    top: int | None,
    pool_filter: str | None,
) -> str:
    """Join rows across `metrics` by (hypothesis_path, hypothesis_hash) and
    sort by the weighted z-normalized composite.

    Each hypothesis must have one row per metric in `metrics` after
    filtering; hypotheses missing any metric are dropped (with a count
    reported in the rendered output).
    """
    if len(metrics) != len(weights):
        raise ValueError(
            f"need one weight per metric; got {len(metrics)} metrics and {len(weights)} weights"
        )
    if normalize not in ("zscore", "none"):
        raise ValueError(f"unknown normalize mode: {normalize!r}")

    if pool_filter:
        rows = [r for r in rows if (_infer_pool(r) or "unspecified") == pool_filter]

    by_metric: dict[str, dict[tuple[str, str], dict]] = {m: {} for m in metrics}
    for row in rows:
        m = row.get("metric")
        if m not in by_metric:
            continue
        key = (row["hypothesis_path"], row["hypothesis_hash"])
        # If multiple rows for the same (path, hash, metric), prefer the most
        # recent (latest ran_at). Re-runs append; the rollup should reflect
        # the freshest score under that snapshot.
        cur = by_metric[m].get(key)
        if cur is None or row.get("ran_at", "") > cur.get("ran_at", ""):
            by_metric[m][key] = row

    # Intersection of keys across all metrics — only hypotheses scored under
    # every requested metric participate in the composite.
    if not metrics:
        return "_(no metrics provided)_\n"
    keys = set(by_metric[metrics[0]])
    for m in metrics[1:]:
        keys &= set(by_metric[m])

    n_intersect = len(keys)
    if not keys:
        return f"_(no hypotheses scored under all of {metrics})_\n"

    ordered_keys = sorted(keys)

    # Per-metric raw scores in the same key order.
    raw: dict[str, list[float]] = {}
    for m in metrics:
        score_key = _primary_score_key_for_metric(m)
        raw[m] = [float(by_metric[m][k].get(score_key, 0.0)) for k in ordered_keys]

    if normalize == "zscore":
        norm = {m: _zscore(raw[m]) for m in metrics}
    else:
        norm = raw

    composites: list[float] = []
    for i in range(len(ordered_keys)):
        composites.append(sum(weights[j] * norm[m][i] for j, m in enumerate(metrics)))

    # Sort by composite desc.
    order = sorted(range(len(ordered_keys)), key=lambda i: -composites[i])
    if top is not None:
        order = order[:top]

    out: list[str] = []
    if pool_filter:
        out.append(f"_(filter: pool={pool_filter!r})_\n")
    out.append("# Composite leaderboard\n")
    out.append(
        f"Metrics: {', '.join(f'{m} (w={w})' for m, w in zip(metrics, weights))}.  "
        f"Normalization: {normalize}.  "
        f"Hypotheses scored under all metrics: {n_intersect}."
    )
    out.append("")
    header_cells = ["rank", "composite"]
    for m in metrics:
        if normalize == "zscore":
            header_cells.append(f"{m} (z)")
        header_cells.append(m)
    header_cells += ["hypothesis", "ran_at_v1"]
    out.append("| " + " | ".join(header_cells) + " |")
    out.append("|---:|---:|" + "---:|" * (len(header_cells) - 3) + "---|---|")
    primary_metric = metrics[0]
    for rank, i in enumerate(order, 1):
        k = ordered_keys[i]
        cells = [str(rank), f"{composites[i]:+.4f}"]
        for j, m in enumerate(metrics):
            if normalize == "zscore":
                cells.append(f"{norm[m][i]:+.4f}")
            cells.append(f"{raw[m][i]:+.4f}")
        cells.append(f"`{k[0]}`")
        cells.append(by_metric[primary_metric][k].get("ran_at", ""))
        out.append("| " + " | ".join(cells) + " |")
    out.append("")
    return "\n".join(out) + "\n"


def render(
    rows: list[dict],
    metric_filter: str | None,
    pool_filter: str | None,
    top: int | None,
    by_source_pool: bool,
) -> str:
    if pool_filter:
        rows = [r for r in rows if (_infer_pool(r) or "unspecified") == pool_filter]

    by_metric: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        m = row.get("metric")
        if metric_filter and m != metric_filter:
            continue
        by_metric[m].append(row)

    if not by_metric:
        return "_(no result rows match)_\n"

    out: list[str] = []
    if pool_filter:
        out.append(f"_(filter: pool={pool_filter!r})_\n")

    for metric in sorted(by_metric):
        group_all = by_metric[metric]
        n_total = len(group_all)
        s = None
        if metric == "local_fit_v0":
            zs = [float(r.get("score_control_z", 0.0)) for r in group_all]
            s = _stats(zs)
        out.append(f"## {metric} ({n_total} rows)\n")
        if s is not None:
            out.append(
                "Distribution: "
                f"mean z = {s['mean']:+.4f}, "
                f"median = {s['median']:+.4f}, "
                f"sd = {s['sd']:.4f}; "
                f"n(z>+1) = {s['n_z_gt_1']} ({100 * s['n_z_gt_1'] / s['n']:.1f}%), "
                f"n(z>+2) = {s['n_z_gt_2']} ({100 * s['n_z_gt_2'] / s['n']:.1f}%), "
                f"n(z<-1) = {s['n_z_lt_neg1']} ({100 * s['n_z_lt_neg1'] / s['n']:.1f}%)."
            )
            out.append("")

        ordered = sorted(group_all, key=_sort_key, reverse=True)
        if top is not None:
            ordered = ordered[:top]
        if metric == "local_fit_v0":
            out.extend(_render_local_fit(ordered))
        elif metric == "local_fit_v1":
            out.extend(_render_local_fit_v1(ordered))
        elif metric == "geographic_genre_fit_v1":
            out.extend(_render_geographic_genre(ordered))
        else:
            out.extend(_render_compression_delta(ordered))
        out.append("")

    if by_source_pool:
        local_fit_rows = [
            r for r in rows if r.get("metric") == "local_fit_v0"
        ]
        if local_fit_rows:
            out.append("")
            out.extend(_render_per_pool_summary(local_fit_rows, top or 10))

    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--results",
        type=Path,
        default=_DEFAULT_RESULTS,
        help="Path to results/experiments.jsonl (default: %(default)s).",
    )
    parser.add_argument("--metric", default=None, help="Restrict to a single metric name.")
    parser.add_argument(
        "--pool",
        default=None,
        help="Restrict to a single source pool (inferred from hypothesis_path under "
        "hypotheses/auto/<pool>/).",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=None,
        help="Show only the top N rows per metric (default: all).",
    )
    parser.add_argument(
        "--by",
        choices=["source-pool"],
        default=None,
        help="Append a grouped summary section. 'source-pool' groups local_fit_v0 "
        "rows by inferred source pool.",
    )
    parser.add_argument(
        "--metrics",
        default=None,
        help="Comma-separated metric list for the COMPOSITE leaderboard "
        "(e.g. 'local_fit_v1,geographic_genre_fit_v1'). Mutually exclusive "
        "with --metric.",
    )
    parser.add_argument(
        "--weights",
        default=None,
        help="Comma-separated weights matching --metrics (e.g. '0.7,0.3'). "
        "Required with --metrics.",
    )
    parser.add_argument(
        "--normalize",
        choices=["zscore", "none"],
        default="zscore",
        help="Per-metric normalization for the composite ranking. Default: zscore.",
    )
    parser.add_argument(
        "--write",
        type=Path,
        default=None,
        help="Write the rendered markdown to this path instead of stdout. The file "
        "is committed-quality output (deterministic given the result stream).",
    )
    args = parser.parse_args(argv)

    rows = load_rows(args.results)
    if args.metrics:
        if args.metric:
            parser.error("--metric and --metrics are mutually exclusive")
        if not args.weights:
            parser.error("--weights is required with --metrics")
        metrics = [m.strip() for m in args.metrics.split(",") if m.strip()]
        weights = [float(w.strip()) for w in args.weights.split(",") if w.strip()]
        text = _render_composite(
            rows,
            metrics=metrics,
            weights=weights,
            normalize=args.normalize,
            top=args.top,
            pool_filter=args.pool,
        )
    else:
        text = render(
            rows,
            metric_filter=args.metric,
            pool_filter=args.pool,
            top=args.top,
            by_source_pool=(args.by == "source-pool"),
        )
    if args.write:
        args.write.parent.mkdir(parents=True, exist_ok=True)
        args.write.write_text(text, encoding="utf-8")
        print(f"wrote {args.write}", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
